In [1]:
import polars as pl

sales = pl.read_csv('sales_data.csv')

In [2]:
# 1 Which salesperson (by ID) sold the most units in total?

sales_person = (
    sales
    .group_by('Salesperson_ID')
    .agg(
        total_sold = pl.sum('Units_Sold')
    )
    .sort(pl.col('total_sold')).reverse()
)

sales_person
# 61

shape: (99, 2)
┌────────────────┬────────────┐
│ Salesperson_ID ┆ total_sold │
│ ---            ┆ ---        │
│ i64            ┆ i64        │
╞════════════════╪════════════╡
│ 61             ┆ 48235      │
│ 1              ┆ 45123      │
│ 46             ┆ 44874      │
│ 66             ┆ 43697      │
│ 48             ┆ 42720      │
│ …              ┆ …          │
│ 7              ┆ 25809      │
│ 71             ┆ 24618      │
│ 63             ┆ 24428      │
│ 70             ┆ 23975      │
│ 17             ┆ 23591      │
└────────────────┴────────────┘

In [3]:
# 2 Which product (by name) was sold the most in terms of total units? (note: your answer should be  in the form Product_Number, ie Product_1051)
products = (
    sales
    .group_by('Product_Name')
    .agg(
        total_units = pl.sum('Units_Sold')
    )
    .sort(pl.col('total_units')).reverse()
)

products
# Product_1761

shape: (1_000, 2)
┌──────────────┬─────────────┐
│ Product_Name ┆ total_units │
│ ---          ┆ ---         │
│ str          ┆ i64         │
╞══════════════╪═════════════╡
│ Product_1761 ┆ 5081        │
│ Product_1411 ┆ 4958        │
│ Product_1341 ┆ 4944        │
│ Product_1743 ┆ 4912        │
│ Product_1766 ┆ 4900        │
│ …            ┆ …           │
│ Product_1482 ┆ 2095        │
│ Product_1704 ┆ 2033        │
│ Product_1586 ┆ 2008        │
│ Product_1842 ┆ 1910        │
│ Product_1195 ┆ 1866        │
└──────────────┴─────────────┘

In [4]:
# 3 Which region had the highest dollar sales in the month of January?

sales1 = sales.filter(pl.col('Month') == 1)

sales_jan = (
    sales1
    .group_by('Region')
    .agg(
        total_units = pl.sum('Total_Sale')
    )
    .sort(pl.col('total_units')).reverse()
)

sales_jan
# east

shape: (4, 2)
┌────────┬─────────────┐
│ Region ┆ total_units │
│ ---    ┆ ---         │
│ str    ┆ i64         │
╞════════╪═════════════╡
│ East   ┆ 18184696    │
│ South  ┆ 18152570    │
│ West   ┆ 17865245    │
│ North  ┆ 17533368    │
└────────┴─────────────┘

In [5]:
# 4 Which salesperson (by ID) sold the fewest units in the North region?

sales_north = sales.filter(pl.col('Region') == 'North')

sales_person_north = (
    sales_north
    .group_by('Salesperson_ID')
    .agg(
        total_units = pl.sum('Units_Sold')
    )
    .sort(pl.col('total_units'))
)

sales_person_north
# 63

shape: (99, 2)
┌────────────────┬─────────────┐
│ Salesperson_ID ┆ total_units │
│ ---            ┆ ---         │
│ i64            ┆ i64         │
╞════════════════╪═════════════╡
│ 63             ┆ 5374        │
│ 7              ┆ 5530        │
│ 70             ┆ 5598        │
│ 34             ┆ 5647        │
│ 42             ┆ 5866        │
│ …              ┆ …           │
│ 48             ┆ 10739       │
│ 46             ┆ 11763       │
│ 18             ┆ 12051       │
│ 61             ┆ 12733       │
│ 1              ┆ 12960       │
└────────────────┴─────────────┘

In [6]:
# 5 What is the average unit price for products sold by Sales person 14?
# Note: For this question, assume that the "average unit price" refers to the simple average price of all products sold by Salesperson 14. 

sales_14 = sales.filter(pl.col('Salesperson_ID') == 14)

sales_14_price = sales_14["Unit_Price"].mean()

sales_14_price
# 261

261.4578313253012

In [7]:
# 6 Someone tells you: the simple price averages computed above are not accurate representatives of the "average" price in a market. 
# For example, say there are only two products 1 and 2 with unit prices $20 and $500. 
# Suppose you sell 50 units of the first product and only 5 units of the second product. 
# Then (20+500)/2 = $260 is the simple price average. 
# That is clearly not representative of the typical price paid in the market since 50/55 = 91%  of all products sold were priced at $20! 
# A better average is a sales-weighted average, ie (20*50 + 5*500)/(50 + 5) = $63.6. This average gives higher weight to products that had higher sales.
# Calculate the average sales-weighted unit price for products sold by Sales person 14 (round to nearest integer)

# Calculate the sales-weighted average unit price
sales_weighted_avg_price = (
    (sales_14['Unit_Price'] * sales_14['Units_Sold']).sum() /
    sales_14['Units_Sold'].sum()
)

print(sales_weighted_avg_price)
# 266

265.66515409836063

In [8]:
# 7 Which salesperson in the East region had the highest total sales (dollar sales)?

sales_east = sales.filter(pl.col('Region') == 'East')

sales_person_east = (
    sales_east
    .group_by('Salesperson_ID')
    .agg(
        total_sales = pl.sum('Total_Sale')
    )
    .sort(pl.col('total_sales')).reverse()
)

sales_person_east
# 14

shape: (99, 2)
┌────────────────┬─────────────┐
│ Salesperson_ID ┆ total_sales │
│ ---            ┆ ---         │
│ i64            ┆ i64         │
╞════════════════╪═════════════╡
│ 14             ┆ 3109998     │
│ 61             ┆ 3074226     │
│ 56             ┆ 2873571     │
│ 96             ┆ 2855345     │
│ 19             ┆ 2839222     │
│ …              ┆ …           │
│ 30             ┆ 1427904     │
│ 25             ┆ 1413955     │
│ 51             ┆ 1349273     │
│ 71             ┆ 1336251     │
│ 70             ┆ 1199723     │
└────────────────┴─────────────┘

In [9]:
# 8 What was the Product_Name of the product with the highest unit sales in the South region? 
# (your answer should be product_1000 if product id = 1000 was the the most sold product)

sales_south = sales.filter(pl.col('Region') == 'South')

sales_south_product = (
    sales_south
    .group_by('Product_Name')
    .agg(
        total_units = pl.sum('Units_Sold')
    )
    .sort(pl.col('total_units')).reverse()
)

sales_south_product
# Product_1106

shape: (1_000, 2)
┌──────────────┬─────────────┐
│ Product_Name ┆ total_units │
│ ---          ┆ ---         │
│ str          ┆ i64         │
╞══════════════╪═════════════╡
│ Product_1106 ┆ 1814        │
│ Product_1072 ┆ 1781        │
│ Product_1227 ┆ 1753        │
│ Product_1629 ┆ 1746        │
│ Product_1903 ┆ 1686        │
│ …            ┆ …           │
│ Product_1810 ┆ 272         │
│ Product_1038 ┆ 228         │
│ Product_1690 ┆ 212         │
│ Product_1040 ┆ 206         │
│ Product_1586 ┆ 196         │
└──────────────┴─────────────┘

In [10]:
# 9 In which month was the highest number of units sold in the East region?

sales_east_month = (
    sales_east
    .group_by('Month')
    .agg(
        total_units = pl.sum('Units_Sold')
    )
    .sort(pl.col('total_units')).reverse()
)

sales_east_month
# may 5

shape: (12, 2)
┌───────┬─────────────┐
│ Month ┆ total_units │
│ ---   ┆ ---         │
│ i64   ┆ i64         │
╞═══════╪═════════════╡
│ 5     ┆ 74229       │
│ 6     ┆ 73852       │
│ 3     ┆ 73689       │
│ 1     ┆ 73391       │
│ 7     ┆ 71019       │
│ …     ┆ …           │
│ 8     ┆ 70182       │
│ 9     ┆ 69263       │
│ 11    ┆ 67524       │
│ 4     ┆ 66108       │
│ 2     ┆ 64161       │
└───────┴─────────────┘

In [11]:
# 10 In this question you are asked to compute average dollar sales (Total_Sale) for each of the four regions for each product. 

# sales_region_south = (
#     sales_south
#     .group_by( 'Product_Name')
#     .agg(
#         total_sales = pl.mean('Total_Sale')
#     )
#     .sort(pl.col('total_sales')).reverse()
# )

# print(sales_region_south.head(10))

# sales_region_product_east = (
#     sales_east
#     .group_by( 'Product_Name')
#     .agg(
#         total_sales = pl.mean('Total_Sale')
#     )
#     .sort(pl.col('total_sales')).reverse()
# )
# # print(sales_region_product_east.head(10))

# sales_west = sales.filter(pl.col('Region') == 'West')


# sales_region_product_west = (
#     sales_west
#     .group_by( 'Product_Name')
#     .agg(
#         total_sales = pl.mean('Total_Sale')
#     )
#     .sort(pl.col('total_sales')).reverse()
# )

# # print(sales_region_product_west.head(10))

# sales_region_product_n = (
#     sales_north
#     .group_by( 'Product_Name')
#     .agg(
#         total_sales = pl.mean('Total_Sale')
#     )
#     .sort(pl.col('total_sales')).reverse()
# )
# sales_region_product_n.head(10)


# correct answer
sales_region_product = (
    sales
    .group_by('Region', 'Product_Name')
    .agg(
        total_sales = pl.mean('Total_Sale')
    )
    .sort(pl.col('total_sales')).reverse()
)

sales_region_product.head(10)
# sales_region_product.head(10)
# "North"	"" Product_1525
# "East"	"" Product_1624
# "South"	"" Product_1599
# "West"	"" Product_1558

shape: (10, 3)
┌────────┬──────────────┬──────────────┐
│ Region ┆ Product_Name ┆ total_sales  │
│ ---    ┆ ---          ┆ ---          │
│ str    ┆ str          ┆ f64          │
╞════════╪══════════════╪══════════════╡
│ West   ┆ Product_1558 ┆ 52053.333333 │
│ North  ┆ Product_1525 ┆ 50470.0      │
│ West   ┆ Product_1913 ┆ 48917.222222 │
│ North  ┆ Product_1918 ┆ 48633.272727 │
│ West   ┆ Product_1056 ┆ 48206.583333 │
│ West   ┆ Product_1685 ┆ 45600.0      │
│ East   ┆ Product_1624 ┆ 45477.0      │
│ West   ┆ Product_1340 ┆ 45279.0      │
│ East   ┆ Product_1735 ┆ 44642.923077 │
│ South  ┆ Product_1599 ┆ 44419.375    │
└────────┴──────────────┴──────────────┘

In [12]:
# 11 Finally, let's look at the effect of salesperson experience on dollar sales (Total_Sale). 
# Define "inexperienced" salespeople as having 5 years or less of sales experience and let the rest (more than 5 years of experience) be "experienced" salespeople. 
# What is the average increase in sales across all products due to experience? 
# To answer this, find the average increase in sales for experienced salespeople compared to inexperienced salespeople for each product and then compute the average increase across all products. 
# So you need to find (1) average dollar sales for each product for experienced and inexperienced salespeople (2) find the difference between the two and then (3) find the average difference across all products. 
# Report your answer as rounded to the nearest integer. 

# Step 1: Categorize salespeople by experience

sales = sales.with_columns(
    pl.when(pl.col('Salesperson_Experience') > 5)
    .then(pl.lit('Experienced'))
    .otherwise(pl.lit('Inexperienced'))
    .alias('Experience_Category')
)


print(sales.select(['Salesperson_Experience', 'Experience_Category']).head())

print(type(sales))

avg_sales_by_experience = (
    sales.
    group_by(['Product_ID', 'Experience_Category'])
    .agg([pl.col('Total_Sale').mean().alias('Avg_Total_Sale')])
    .pivot(values='Avg_Total_Sale', index='Product_ID', columns='Experience_Category')
)


# Step 3: Calculate the difference in average sales between experienced and inexperienced salespeople
avg_sales_by_experience = (
    avg_sales_by_experience
    .with_columns(
        (pl.col('Experienced') - pl.col('Inexperienced')).alias('Sales_Difference')
        )
)
print(avg_sales_by_experience.head())

# Step 4: Compute the average increase across all products
# average_increase = avg_sales_by_experience.select(pl.col('Sales_Difference').mean())[0, 0]
average_increase = avg_sales_by_experience["Sales_Difference"].mean()

print(average_increase)

# 4603 correct

shape: (5, 2)
┌────────────────────────┬─────────────────────┐
│ Salesperson_Experience ┆ Experience_Category │
│ ---                    ┆ ---                 │
│ i64                    ┆ str                 │
╞════════════════════════╪═════════════════════╡
│ 6                      ┆ Experienced         │
│ 19                     ┆ Experienced         │
│ 28                     ┆ Experienced         │
│ 14                     ┆ Experienced         │
│ 10                     ┆ Experienced         │
└────────────────────────┴─────────────────────┘
<class 'polars.dataframe.frame.DataFrame'>
shape: (5, 4)
┌────────────┬──────────────┬───────────────┬──────────────────┐
│ Product_ID ┆ Experienced  ┆ Inexperienced ┆ Sales_Difference │
│ ---        ┆ ---          ┆ ---           ┆ ---              │
│ i64        ┆ f64          ┆ f64           ┆ f64              │
╞════════════╪══════════════╪═══════════════╪══════════════════╡
│ 1878       ┆ 28375.428571 ┆ 18904.0       ┆ 9471.428571      │
│ 1422       ┆ 1298.625     ┆ 841.5         ┆ 457.125          │
│ 1435       ┆ 26082.0      ┆ 16249.5       ┆ 9832.5           │
│ 1483       ┆ 2609.894737  ┆ 1728.571429   ┆ 881.323308       │
│ 1218       ┆ 20564.06383  ┆ 18180.4       ┆ 2383.66383       │
└────────────┴──────────────┴───────────────┴──────────────────┘
4603.4130256198405

/tmp/ipykernel_17673/3414234629.py:26: DeprecationWarning: The argument `columns` for `DataFrame.pivot` is deprecated. It has been renamed to `on`.
  .pivot(values='Avg_Total_Sale', index='Product_ID', columns='Experience_Category')